### ISSUE TITLE
Add Arrows for navigation when Image is in full resolution

### ISSUE THREAD

**Issue by joeabn** [ericleong/zoomwall.js#14]
it will be nice to have some arrows shown after you click on a specific picture for navigation between full resolution pictures, or adding a swipe feature for touch devices.

**Comment by ericleong** [comment]
* Arrows are surprisingly tricky in this library as the image elements are still "contained" by their container. What this means in practice is that you can still scroll the page and see other images. For arrows, this means the arrows need to be placed next to the image to make sense, but `:before` and `:after` pseudo-elements can't be accessed by Javascript, which would be necessary since the images are positioned via CSS `translate`. This issue can be fixed with `position: fixed`. which is probably the more "conventional" lightbox implementation, but this is a pretty major undertaking.
* A swipe feature is a great idea, but also note the odd quirk that when the user reaches the end of a "row" they will still swipe left to access the next image on the left side of the next row. This feels somewhat awkward.

Ultimately I admit this project does have poor user experience but it was primarily an aesthetically-driven project rather than a user-experience-driven one. I'd recommend a more "conventional" image gallery library like [PhotoSwipe](https://photoswipe.com/) if you need a higher-quality user experience.

I have an idea for another image gallery library that rearranges all the images horizontally in lightbox mode using an animation, and that library could accommodate your suggestions.
