### ISSUE TITLE
Zoom issue when less image

### ISSUE THREAD

**Issue by duongtv** [ericleong/zoomwall.js#6]
Hello there,

I have created a sample page. It seems zoom feature does not work if there is too less images on the page. E.g: there is only 4 images.

Can you please look at this case?

Thanks

**Comment by ericleong** [comment]
The best solution depends on your page layout, but setting a fixed height on your container element (the one that has the `zoomwall` class) will scale the image to that height. The issue of course that now the container element is huge, so you could make it applicable only when in zoomed in:

```css
.zoomwall.lightbox {
    min-height: 100vh;
}
```

It will look a little strange because the element needs to expand, of course. See https://github.com/ericleong/zoomwall.js/issues/3#issuecomment-150736805 for another solution.
